# Define a versão do Docker Compose. '3.8' é uma boa escolha moderna.
version: '3.8'

# 'services' é onde definimos nossos contêineres.
services:
  # 'rustdesk' é o nome que damos ao nosso serviço.
  rustdesk:
    # Em vez de puxar uma imagem pronta, instrui o Compose a construir
    # a imagem a partir do Dockerfile no diretório atual ('.').
    build: .
    # Dá um nome específico ao contêiner, o mesmo que --name.
    container_name: ${CONTAINER_NAME}
    # Equivalente a --restart unless-stopped.
    restart: unless-stopped
    # Equivalente a -v rustdesk-data:/data.
    # O volume 'rustdesk_data' será definido no final do arquivo.
    volumes:
      - rustdesk_data:/data
    # Aqui passamos as variáveis de ambiente, lendo do nosso arquivo .env
    # A sintaxe ${VARIAVEL} é como o Compose substitui os valores.
    environment:
      - TS_AUTH_KEY=${TS_AUTH_KEY}
      - TS_HOSTNAME=${TS_HOSTNAME}
    # Equivalente a --device=/dev/net/tun:/dev/net/tun
    devices:
      - /dev/net/tun:/dev/net/tun
    # Equivalente a --cap-add=NET_ADMIN
    cap_add:
      - NET_ADMIN

# 'volumes' é onde declaramos os volumes nomeados que usamos nos serviços.
# Isso garante que o Docker gerencie o volume corretamente.
volumes:
  rustdesk_data: